name: Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  publish:
    name: Publish to Marketplace
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install vsce
      run: npm install -g @vscode/vsce
    
    - name: Run tests
      run: |
        npm run lint
        npm run compile
        npm run test:unit
      continue-on-error: true
    
    - name: Update version (if manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    
    - name: Get version from package.json
      if: github.event_name == 'release'
      run: |
        echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    
    - name: Package extension
      run: vsce package --no-dependencies
    
    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish -p $VSCE_PAT
      continue-on-error: true  # Allow to fail if token not set
    
    - name: Publish to Open VSX Registry
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
      run: |
        npm install -g ovsx
        ovsx publish *.vsix -p $OVSX_PAT
      continue-on-error: true  # Allow to fail if token not set
    
    - name: Upload VSIX to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./slim-to-erb-${{ env.VERSION }}.vsix
        asset_name: slim-to-erb-${{ env.VERSION }}.vsix
        asset_content_type: application/zip
    
    - name: Create GitHub Release (if manual)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        files: '*.vsix'
        body: |
          ## Slim to ERB Converter v${{ github.event.inputs.version }}
          
          ### Installation
          1. Download the `.vsix` file from the assets below
          2. Open VS Code
          3. Go to Extensions view (Ctrl+Shift+X)
          4. Click on the "..." menu and select "Install from VSIX..."
          5. Select the downloaded file
          
          ### Changes
          - See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details
        token: ${{ secrets.GITHUB_TOKEN }}